spring:
  application:
    name: danafix-product
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/danafix
    username: postgres
    password: root
  jpa:
    show-sql: false